### PR TITLE
refactor, generate typedefs

### PR DESCRIPTION
**Pull request by lostfictions**
~EDIT: should be ready to go, except that we have another module that doesn't include compiled sources now. My recommendation as usual, is just that we do the normal simple thing and publish to npm instead of building even more hacky infrastructure to make its dependents build it, but it's up to you.~

now a published npm package, but under my own personal account. let me know who i should share access with

---

comments welcome re: approach for generation, located at https://github.com/PeerioTechnologies/peerio-translator/blob/refactor/src/generate/generate-defs.ts

still needed:
- ~ability to not require registered tags like `<b>`, `<i>`, etc. (just predefine them?)~ `<b>`, `<i>`, and `<br/>` are not required params
- ~ditto for urls~ `<a-whatever>` are not required params
- ~probably just use `React.Children[]` instead of a full tuple type for return signature; it's noisy but doesn't win us anything.~ done

### CODE REVIEW

**Comment by lostfictions** [comment]
@anri-asaturov pretty much ready for review, we just need to decide how consumers get the compiled version. can we just publish it to npm?

**Comment by anri-asaturov** [comment]
Compiled version of translation? 
Well, the translation file is in the sdk currently, and clients currently compile their own sdk, so I guess that's the easiest solution atm that will fit the current workflow?

**Comment by lostfictions** [comment]
@anri-asaturov so clients will install the sdk, compile it, and then the sdk will compile the translation library? or every consumer of the sdk will add extra code to compile the translation library as well?

i.... just published the compiled version to npm. can this just be like a normal, easy unsurprising npm library? like peerio-updater?

**Comment by anri-asaturov** [comment]
My suggestion is for clients to treat en.json as a source file to compile yes.
Unless I'm missing something. How would we publish compiled version to NPM from every branch? If we don't do that - then effectively you can never merge PR, because it will never pass the checks :-D

**Comment by anri-asaturov** [comment]
Oh, crap, sorry. You mean compiled version of translator? Yeah, for sure, npm it is.

**Comment by lostfictions** [comment]
@anri-asaturov sorry we're talking about two separate things. this library is in typescript now, so the compiled sources need to end up on the client somehow.

building the typedefs for a locale file is accomplished via a cli command which is available to consumers postinstall, so that's not a big problem -- i'll be adding that to icebear shortly.

**Comment by anri-asaturov** [comment]
Safe to merge?

**Comment by lostfictions** [comment]
maybe wait until the icebear pr to verify it works in a running environment, etc.

**Pull request merged**
